#!/usr/bin/env python3
import sys

from ocflib.misc import mail


if __name__ == '__main__':
    mail.send_mail(
        mail.MAIL_ROOT,
        '[ldapsync] Problem report',
        sys.stdin.read(),
        sender='ldapsync <root@ocf.berkeley.edu>',
    )
