#!/usr/bin/env python3
import sys

from ocflib.misc import mail


if __name__ == '__main__':
    stdin_str = sys.stdin.read()
    if stdin_str:
        mail.send_mail(
            mail.MAIL_ROOT,
            '[ldapsync] Problem report',
            stdin_str,
            sender='ldapsync <root@ocf.berkeley.edu>',
        )
